### ISSUE TITLE
Multi-site support

### ISSUE THREAD

**Issue by horlszone** [BVNetwork/404handler#13]
Hi,

Great module, and really loving the latest development, thanks!

We've used older versions of this module for some time now on various projects, however, we would like to use the latest version on EPiServer 9 and above, however, we found that it doesn't support multi-site. In the past we'd had to implement custom code, and wondering if there are any plans to allow multi-site?

Would an implementation probably involve using SiteDefinition.Current, an SQL table change, DDS change, and other bits and pieces for loading multiple handlers?

Thanks,
Steven

**Comment by permagne** [comment]
Hi,
you should be able to use absolute urls in order to get site specific redirects in a multi-site setup. I know a few sites where this has been done with success

**Comment by horlszone** [comment]
Hi,

Thanks, that would work, just means couldn't then use relative URL's at all, otherwise all sites would try to redirect the page.

**Comment by evest** [comment]
True, but only IF there is a 404 happening in the first place.
