### ISSUE TITLE
Use language path in URL

### ISSUE THREAD

**Issue by JanakaEPiServer** [BVNetwork/404handler#15]
Thinking of using MVC and not applying a single generic 404 page so that you could have different pages for each language. 
e.g.
/en/404
/sv/404

Is it possible to configure the language code into the path for the 404 request?

**Comment by permagne** [comment]
The NotFoundPage attribute, which should be used on your controller, will set the correct language based on the requested page. So if a user requests /sv/whatever and gets a 404, the current language will be set to swedish. 
I don't see why you would need different paths, as the the visitor should never see the actual path to the 404 page
