### ISSUE TITLE
Add EPi 10 support

### ISSUE THREAD

**Issue by marisks** [BVNetwork/404handler#17]

**Comment by evest** [comment]
Man, it is one day old, give me a break :-) I'll get to it shortly!

**Comment by marisks** [comment]
@frederikvig made pull request for this: https://github.com/BVNetwork/404handler/pull/18

**Comment by frederikvig** [comment]
@evest try to keep up old man ^^

**Comment by evest** [comment]
Yeah yeah yeah... It needs more work though, we're maintaining 2 major versions from the same repo, soon 3 :-)

**Comment by appendix68** [comment]
One more here awaiting this.. :) Awesome job!

**Comment by evest** [comment]
The current versioning is going to be a problem. I'm considering bumping it to the same major as Episerver.Core. What do you think?

**Comment by evest** [comment]
So it would mean the the next version would be 10.0.0, the next change that requires a version bump would be released as 10.0.1, 9.0.1 and 8.0.1. Since we're maintaining all three versions off the same code base, any change should go into all of them, and the versions should align.

**Comment by evest** [comment]
Merged and released. Enjoy! And thanks for the pr @frederikvig!
