### ISSUE TITLE
Create an EPiServer Managed 404 Page

### ISSUE THREAD

**Issue by sayeedchoudhury** [BVNetwork/404handler#2]
Is there any instruction on creating an EPiServer Managed 404 page instead of using the NotFound.aspx page. I had used the instructions on this https://github.com/markeverard/BVN.404Handler.MvcContrib previously to achieve the same functionality. However due to changes with the latest version my code throws an error.

**Comment by permagne** [comment]
With the latest version you do not need to do anything to make it work. You should remove the MvcContrib code - the NotFoundPage attribute is not needed. You can use a standard controller if you want. 
The latest version of the 404 handler will simply look at the end request and handle the 404s there.

I've planned on making a couple of 404 page samples for the Alloy site.

**Comment by sayeedchoudhury** [comment]
Thanks for the quick response. So you are saying I can on the web.config point to any episerver page and the 404 handler will take care of appending the proper Http response code?

**Comment by permagne** [comment]
Yes, that is the idea. Please let me know if you run into any issues.

**Comment by sayeedchoudhury** [comment]
It's working almost. The only issue is it's not returning 404 as the HTTP status code for the page. I guess I will just create a specific controller and override the status code.

**Comment by permagne** [comment]
Yes, you'll have to do that part yourself.

**Comment by evest** [comment]
You can now use the `NotFoundPage` attribute (which is an action filter) on your action in your controller. It will set the status code for you, and also give you the url that could not be found (along with the referer).

See the [readme](https://github.com/BVNetwork/404handler#custom-404-page) for an example.
