### ISSUE TITLE
Latest nuget package not working with language paths

### ISSUE THREAD

**Issue by krelde** [BVNetwork/404handler#20]
I don't know if this is the place to report this.

The nuget package for the 404 is not working with language paths.
Example: 
localhost/[a page that does not exist] - Working with redirect to NotFound.aspx 
localhost/en/[a page that does not exist] - Not working (i get a default 404, not handeld by the module)
localhost/no/[a page that does not exist] - Not working (i get a default 404, not handeld by the module)

However if i download the source code and add the 404 handler to the project manually everything is working as expected.

**Comment by evest** [comment]
That sounds strange. The language code should not have anything to do with the redirect.

Tried on:
http://epicphoto.demo.episerver.no/pagethatdoesnotexist - works
http://epicphoto.demo.episerver.no/en/pagethatdoesnotexist - works
http://epicphoto.demo.episerver.no/no/pagethatdoesnotexist - works

**Comment by krelde** [comment]
Strange.

Maybe it's my settings or something else.

**Comment by krelde** [comment]
Update

When debugging and hitting a 404 with language path i get the following exception.
![image](https://cloud.githubusercontent.com/assets/18183713/20791582/0489e114-b7be-11e6-9723-b39e3eff775d.png)

Can it be related to this conditional if in NotFoundPageUtil.cs?

private static void SetContextLanguage(CultureInfo culture)
        {
#if CMS8
            EPiServer.BaseLibrary.Context.Current["EPiServer:ContentLanguage"] = culture;
#else
            ContextCache.Current["EPiServer:ContentLanguage"] = culture;
#endif
        }

**Comment by evest** [comment]
Oh no! This is a complete disaster. Good catch. Both v9 and v10 packages has the v8 dll file.

It seems that Visual Studio is trying to be smart when building, and picks the previously built dll from the obj directory. And since all projects shares the same obj folder, the first project being built wins.

Good catch, now how do I clean up this mess? I guess I will have to replace the existing v9 and v10 packages and create new versions too. Ouch.

**Comment by evest** [comment]
Closing this, we're building packages in a better way now, so should not happen again.
