### ISSUE TITLE
Clearing server error in global FileNotFoundExceptionHandler obfuscates error logging

### ISSUE THREAD

**Issue by brianweet** [BVNetwork/404handler#26]
The existing Custom404Handler.FileNotFoundExceptionHandler clears the last server error that was thrown. 
In my opinion this is wrong, as the Episerver Global_Error handler will still try to log the error; for us it ends up logging just 

> 2017-02-08 22:23:12,612 [29] ERROR EPiServer.Global: 1.2.5 Unhandled exception in ASP.NET

Without any information on the actual exception which caused the 404.

I propose not clearing the exception, this way we're able to determine what kind of error has been thrown. e.g. 

> 2017-02-08 22:24:35,020 [31] ERROR EPiServer.Global: 1.2.5 Unhandled exception in ASP.NET
System.Web.HttpException (0x80004005): The controller for path '/unknown_path' was not found or does not implement IController.
   at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)
....

We need that information to be able to filter our exceptions. Right now the FileNotFoundExceptionHandler alters the state in such a way that there's no useful information left.

**Comment by evest** [comment]
For the record, this should be in 10.1.1

**Comment by emilssonn** [comment]
@evest, this is still logged without the exception for me. Are you sure this fix is in 10.1.1?
