### ISSUE TITLE
Use of obsolete IDatabaseHandler in DataAccessBaseEx results in NullReferenceException [EpiServer.Framework 10.4.1]

### ISSUE THREAD

**Issue by wanton** [BVNetwork/404handler#28]
After upgrading to EpiServer.Framework 10.4.1 the following lines in DataAccessBaseEx will throw a NullReferenceException. Should be fixable by replacing IDatabaseHandler references with IDatabaseExecutor in DataAccessBaseEx

https://github.com/BVNetwork/404handler/blob/master/src/Core/Data/DataAccessBaseEx.cs#L221
https://github.com/BVNetwork/404handler/blob/master/src/Core/Data/DataAccessBaseEx.cs#L178

**Comment by YauheniButsko** [comment]
Temporary hotfix

`public class CustomBvnDataAccessBaseEx : DataAccessBaseEx
    {
        public CustomBvnDataAccessBaseEx(IDatabaseHandler handler, IDatabaseExecutor executor)
            : base(handler)
        {
            Database = handler;
            Executor = executor;
        }
    }`

`container.For<DataAccessBaseEx>().Use<CustomBvnDataAccessBaseEx>();`

**Comment by evest** [comment]
This has been fixed in [10.1.1](http://nuget.episerver.com/en/OtherPages/Package/?packageId=BVN.404Handler&packageVersion=10.1.1)

**Comment by jonasboman** [comment]
Is there any workaround for CMS 9? IDatabaseExecutor  does not seem to exist in version 9.
