### ISSUE TITLE
404handler broke / BVNetwork.NotFound.Core.CustomRedirects

### ISSUE THREAD

**Issue by AdamSandC** [BVNetwork/404handler#34]
I'm getting the following error and I can no longer use our 404handler. All I was doing was deleting and adding links. It was working fine. How do I fix this? Please help. Thank you.

> An error has occured in the dynamic data store: System.NullReferenceException: Object reference not set to an instance of an object. at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectHandler.LoadCustomRedirects() at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectHandler.get_Current()

~ Adam

![error](https://cloud.githubusercontent.com/assets/14985771/24221694/61ea16e2-0f1d-11e7-8a39-db7baced217f.jpg)

**Comment by evest** [comment]
Hi Adam,
unfortunately, that isn't much information to go on, but is seems like some of the data in the database has been damaged in some way, or that there is data that the handler is unable to read or understand.

Could you provide a debug log (log4net) for when you load the gadget and see the error message? It might have more information to help troubleshoot.

**Comment by AdamSandC** [comment]
We got this fixed. Thank you for reaching out. This was the resolution.

> Epi fixed this. There was a potential issue with the amount of 404 entries in one of the tables associated with the BVN404 Handler. We did some clean up. Then we restarted the Web App and we’re fixed.

~ Adam
