### ISSUE TITLE
Local branch errors

### ISSUE THREAD

**Issue by stgaup** [BVNetwork/404handler#39]
I have downloaded the code locally, and when I try to build it gives some errors.
I am using VS 2017 Pro (on Windows 10 with Creator's Update), and I am also using an EPiServer 10 solution on the same machine.

Severity	Code	Description	Project	File	Line	Suppression State

Error	CS0234	
The type or namespace name 'IDatabaseExecutor' does not exist in the namespace 'EPiServer.Data' (are you missing an assembly reference?)	
BVNetwork.404Handler.Cms9	.\src\Core\Data\DataAccessBaseEx.cs	13

Error	CS0103	
The name 'Executor' does not exist in the current context	
BVNetwork.404Handler.Cms9	.\src\Core\Data\DataAccessBaseEx.cs	16

There are 6 of the second one which seems to be occurring because of the first one.

In the bin folder the EPiServer binaries are of version 9.

**Comment by pettersorby** [comment]
Have you opened the solution without version number?
