### ISSUE TITLE
Version 4.1.0 runtime error

### ISSUE THREAD

**Issue by marcosgc** [BVNetwork/404handler#5]
Hi, 
I've updated the 404handler from version 4.0.4 to 4.1.0. The pagenotfound handler has stopped working. I don't get any redirects to the error page in the bvn404Handler section in web.config. When surfing directly to /notfound.aspx I get the following error:

ERROR EPiServer.Global: 1.2.5 Unhandled exception in ASP.NET
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at BVNetwork.NotFound.Core.NotFoundPage.NotFoundBase.get_UrlNotFound()
   at BVNetwork.NotFound.Core.NotFoundPage.NotFoundBase.OnLoad(EventArgs e)
   at ASP.notfound_aspx.OnLoad(EventArgs e) in c:\EPiServer\Sites\Sandbox\Sandbox\NotFound.aspx:line 45
   at System.Web.UI.Control.LoadRecursive()
...

Tested this on an Alloy site running EPiServer 9.6.1. Any clues on what's wrong?

/Marcos

**Comment by evest** [comment]
Hi Marcos,
I just tried it myself, and get the same behavior. Just a blank page. The status code is 404 though :-)

Turned on logging, and can see that it runs, but no redirect is being done.

Btw, if you surf directly to the notfound.aspx, you need the error path in the query string (as asp.net will do for you automatically.) You should not need the notfound.aspx anymore, you can redirect to whatever you want, and it should still just work.

I'll have to dig a bit.

**Comment by evest** [comment]
Ok, here goes.

Seems it is getting more picky on the configuration. The key is in the `httpErrors` section. It should look something like this:

```xml
<httpErrors errorMode="Custom" existingResponse="Replace">
    <remove statusCode="404" />
    <error statusCode="404" path="/Error/Error404" responseMode="ExecuteURL" />
</httpErrors>
```

Without `errorMode="Custom"`, it won't show the 404 page. Without `existingResponse="Replace"` it won't work for the .aspx extension (and probably some other ones too.)

The path in the `httpErrors` config can point to anything, I've got an Error controller with an Error404 action in my project, and it shows just fint. However, the reported status code will be 202, not 404. To fix this, add the `[BVNetwork.NotFound.Core.NotFoundPage.NotFoundPage]` attribute on your action, and it will fix the status for you. You can also get the url, referer and status code from the ViewBag.

See this for an example:
https://github.com/BVNetwork/CommerceStarterKit/commit/37851dad7d78f34bbddc23e5c65e71d18bcb57a3

**Comment by evest** [comment]
Documentation has been improved, the current version should work OK, but needs correct configuration. We will add a readme to the package to notify users of this during upgrades / installs.

**Comment by marcosgc** [comment]
Thanks! Created a custom controller and view for errorpages. Works great now. The updated doc really helped solve this problem!

Cheers!
