### ISSUE TITLE
Add BVNetwork.404Handler module to web.config transform

### ISSUE THREAD

**Issue by derantell** [BVNetwork/404handler#6]
Installed `v4.1.0` from NuGet and just spent a couple of hours wondering why I the gadget didn't show up in the **Add Gadgets** dialog in the dashboard. Finally I found out that I needed to add the module under the `episerver.shell` config section in **web.config**.

```xml
<episerver.shell>
  <protectedModules>
    <add name="BVNetwork.404Handler" />
  </protectedModules>
</episerver.shell>
```

This should at least be documented in the readme and preferably handled by the web.config transform.

**Comment by evest** [comment]
Agreed!

**Comment by evest** [comment]
Hm, I don't have that in my web.config. And I have the Gadget.
